################################################################################
# Environment script generated by ilcsoft-install on Wed Feb 15 12:12:31 2017
# for Eutelescope located at [ /afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Eutelescope/v1.0 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++"
export ILCSOFT_CMAKE="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/ILCSoft.cmake"
export CC="gcc"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Eutelescope/v1.0/external/eudaq/v1.6.0"
export MILLEPEDEII="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Eutelescope/v1.0/external/millepede2/tags/V04-00-02"
export MILLEPEDEII_VERSION="tags/V04-00-02"
export EUDAQ_VERSION="tags/v1.6.0"
export EUTELESCOPE="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Eutelescope/v1.0"
export PATH="$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/lib:$EUDAQ/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/gear/v01-06"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/root/5.34.30"
export PYTHONPATH="$ROOTSYS/lib:$PYTHONPATH"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/CLHEP/2.1.4.1"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/RAIDA/v01-07"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     MarlinUtil
#--------------------------------------------------------------------------------
export LD_LIBRARY_PATH="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/MarlinUtil/v01-08/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Marlin/v01-09"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/Eutelescope/v1.0/lib/libEutelescope.so:$EUDAQ/lib/libNativeReader.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/lccd/v01-03-01"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/lcio/v02-07-02"
export PYTHONPATH="$LCIO/python:$LCIO/python/examples:$PYTHONPATH"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/usr"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/CED/v01-09-01/bin:$PATH"
export LD_LIBRARY_PATH="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/CED/v01-09-01/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GBL
#--------------------------------------------------------------------------------
export GBL="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/GBL/V01-17-01"
export LD_LIBRARY_PATH="$GBL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------
export PATH="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/CMake/3.5.2/bin:$PATH"


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/afs/desy.de/user/y/yanwing/ILCSOFT/v01-17-10/ilcutil/v01-02-01"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
